name: Nặn File IPA (Bản chuẩn)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Lấy mã nguồn chuẩn của Appium (Mới nhất)
        run: git clone https://github.com/appium/WebDriverAgent.git

      - name: Máy chủ Mac bắt đầu nung code
        run: |
          cd WebDriverAgent
          xcodebuild build-for-testing \
            -project WebDriverAgent.xcodeproj \
            -scheme WebDriverAgentRunner \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO \
            -derivedDataPath ./build

      - name: Đóng gói thành file IPA
        run: |
          cd WebDriverAgent
          mkdir Payload
          cp -r ./build/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app Payload/
          zip -r WebDriverAgentRunner.ipa Payload

      - name: Nhả file IPA cho sếp tải
        uses: actions/upload-artifact@v4
        with:
          name: WebDriverAgentRunner_Cho_3uTools
          path: WebDriverAgent/WebDriverAgentRunner.ipa
